spring:
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:${mysql.port:3306}/kubernetes-letmethink?useUnicode=true&characterEncoding=utf8
    username: ${mysql.usernamea:root}
    password: ${mysql.password:}
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000